### ISSUE TITLE
Show individual dice results

### ISSUE THREAD

**Issue by jcgruenhage** [maubot/dice#1]
Currently, if you put in `!roll 3d20`, the output could be `21` for example, but it could also be `5 + 6 + 10 = 21` for things that might benefit from that.

**Comment by r4dh4l** [comment]
Yes, it would be useful to see doublets/pairs.

**Comment by r4dh4l** [comment]
After playing around with the dice bot I would suggest the following:

# Standard ouput

```
!roll 2d6
10 (4 + 6)
```

# List view

```
!roll 2d6 list
= 10
4
6
```

# Separated view

```
!roll 2d6 sep
4; 6
```

# Separated list view

```
!roll 2d6 seplist
4
6
```

**Comment by r4dh4l** [comment]
@tulir Thx for https://github.com/maubot/dice/commit/98e6e5baa314a4668e36e8e094b678ab19921a84 - will there be a new release or should we just patch the file manually?
